{{ if eq .Values.vault.type "nfs" }}
{{- range $i, $chaincode := $.Values.network.chaincodes }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hlf-chaincode--{{ $chaincode.name | lower }}-pvc
spec:
{{/*  volumeName: {{ $.Values.vault.nfs.volumeName }}*/}}
  accessModes:
    - ReadWriteMany
  storageClassName: {{ $.Values.vault.nfs.storageClass }}
  resources:
    requests:
      storage: {{ $.Values.vault.nfs.pvc_size }}
---
{{- end }} {{- /* network chaincodes */ -}}
{{- end }}
