{{ if eq .Values.vault.type "nfs" }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: channel-artifacts
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ $.Values.vault.nfs.storageClass }}
  resources:
    requests:
      storage: {{ $.Values.vault.nfs.pvc_size }}

---
{{- end }} {{- /* pvc */ -}}

