{{ if eq .Values.vault.type "nfs" }}
{{- range $i, $org := .Values.PeerOrgs }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hlf-ca--{{ $org.Name | lower }}
spec:
{{/*  volumeName: {{ $.Values.vault.nfs.volumeName }}*/}}
  accessModes:
    - ReadWriteMany
  storageClassName: {{ $.Values.vault.nfs.storageClass }}
  resources:
    requests:
      storage: {{ $.Values.vault.nfs.pvc_size }}
---
{{- end }} {{- /* Peer Orgs */ -}}
{{- end }}
