{{- range $i, $org := .Values.PeerOrgs }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hlf-ca--{{ $org.Name | lower }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hlf-ca--{{ $org.Name | lower }}
  template:
    metadata:
      labels:
        app: hlf-ca--{{ $org.Name | lower }}
    spec:
  #volumeClaimTemplates:
  #{{- if $.Values.orderer.persistence.enabled }}
  - metadata:
      name: hlf-ca--{{ $org.Name | lower }}
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: {{ $.Values.persistence.storageClass }}
      resources:
        requests:
          storage: {{ $.Values.orderer.persistence.size }}
  #{{- end }}
      volumes:
      # name: ca-tls
      #  secret:
      #    secretName: hlf-ca--{{ $org.Name | lower }}-tls
      - name: hlf-scripts
        configMap:
          name: hlf-scripts
          defaultMode: 0777
      - name: fabric-ca-config
        configMap:
          name: hlf-fabric-ca-config
          defaultMode: 0777
      - name: hlf-ca--{{ $org.Name | lower }}
        persistentVolumeClaim:
          claimName: hlf-ca--{{ $org.Name | lower }}
      containers:
      - name: ca
        image: hyperledger/fabric-ca:{{ $.Values.hyperledgerCaVersion }}
        command: ["sh", "-c", "/hlf-scripts/start-root-ca.sh"]
        volumeMounts:
        - mountPath: /{{ $org.Domain }}/fabric-ca
          name: hlf-ca--{{ $org.Name | lower }}
        - mountPath: /hlf-scripts
          name: hlf-scripts
        - mountPath: /hlf_config/fabric-ca-config
          name: fabric-ca-config

        env:
        - name: FABRIC_CA_NAME
          value: {{ printf "ca-%s" $org.Name }}
        - name: FABRIC_CA_HOME
          value: /{{ $org.Domain }}/fabric-ca
        - name: CA_HOST
          value: hlf-ca--{{ $org.Name | lower }}
---
{{- end }} {{- /* Orgs */ -}}
