{{ if eq .Values.vault.type "nfs" }}
{{- range $i, $org := .Values.PeerOrgs }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hlf-peer-org--{{ $org.Name | lower }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ $.Values.vault.nfs.storageClass }}
  resources:
    requests:
      storage: {{ $.Values.vault.nfs.pvc_size }}

---
{{- end }} {{- /* Peer Orgs */ -}}
{{- end }} {{- /* pvc */ -}}

