#debug: {{ $debug }}
#
#tls:
#  enabled: {{ $tls_enable }}
#  certfile: {{ $tls_certfile }}
#  keyfile: {{ $tls_keyfile }}
#
#ca:
#  name: {{ $ca_name }}
#  keyfile: {{ $ca_keyfile }}
#  certfile: {{ $ca_certfile }}


# Version of config file
version: 1.4.9

# Server's listening port (default: 7054)
port: 7054

# Enables debug logging (default: false)
debug: true

# Size limit of an acceptable CRL in bytes (default: 512000)
crlsizelimit: 512000

tls:
  # Enable TLS (default: false)
  enabled: true
  # TLS for the server's listening port
  certfile:
  keyfile:
  clientauth:
    type: noclientcert
    certfiles:

ca:
  # Name of this CA
  name:
  # Key file (is only used to import a private key into BCCSP)
  keyfile:
  # Certificate file (default: ca-cert.pem)
  certfile:
  # Chain file
  chainfile:

registry:
  # Maximum number of times a password/secret can be reused for enrollment
  # (default: -1, which means there is no limit)
  maxenrollments: -1

  # Contains identity information which is used when LDAP is disabled
  identities:
    - name: admin
      pass: adminpw
      type: client
      affiliation: ""
      attrs:
        hf.Registrar.Roles: "*"
        hf.Registrar.DelegateRoles: "*"
        hf.Revoker: true
        hf.IntermediateCA: true
        hf.GenCRL: true
        hf.Registrar.Attributes: "*"
        hf.AffiliationMgr: true

db:
  type: sqlite3
  datasource: fabric-ca-server.db
  tls:
    enabled: false
    certfiles:
    client:
      certfile:
      keyfile:

affiliations:
  amvoxdlt:
    - admin
    - orderer
    - user
  amvox:
    - admin
    - user
  org1:
    - user
  org2:
    - user