# Default values for artifacts-workflow.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# number of times to retry a failed leaf task
retryCount: 4

hyperledgerVersion: 2.2.1
FabricCaClientVersion: 1.4.9

# see the Raft sample in the README for how to enable TLS
tlsEnabled: true

# use actual domain names like peer0.atlantis.com instead of internal service names
# this should be set to true for TLS
useActualDomains: true
logLevel: info
adminCerts: true
ca:
  userName: admin
  password: adminpw
  logLevel: info
  ingress:
    enabled: false

flow:
  orderer:
    # run orderer  certificate generation in parallel
    parallel: false
  peerorgs:
    # run peer org  certificate generation in parallel
    parallel: false
    
    
  